// Generated by CoffeeScript 1.4.0
(function() {
  var mongoose;

  mongoose = require("mongoose");

  exports.timestamps = function(schema, options) {
    if (!options) {
      options = {};
    }
    schema.add({
      stats: {
        createdAt: Date,
        lastModified: Date
      }
    });
    return schema.pre("save", function(next) {
      if (!this.stats.createdAt) {
        this.stats.createdAt = this.stats.lastModified = new Date;
      } else {
        this.stats.lastModified = new Date;
      }
      return next();
    });
  };

}).call(this);
